### ISSUE TITLE
Error while issuing Vcs

### ISSUE THREAD

**Issue by philpotisk** [walt-id/.github#20]
### Discussed in https://github.com/walt-id/.github/discussions/17

<div type='discussions-op-text'>

<sup>Originally posted by **SethiShivam** October 12, 2022</sup>
Hi team , 

I am trying to run ssi kit examples

When ever I try to execute this piece of code  to issue  credentials . 

    **public ProofConfig createProofConfig(String issuerDid, String subjectDid, ProofType proofType, Instant expiration) {
    	
        return new ProofConfig(issuerDid, subjectDid, null, null, proofType, null, null,
                null, null, null, null, expiration, null, null, null, null);
    }**

**I get the following error** :

java.lang.NullPointerException: Parameter specified as non-null is null: method id.walt.signatory.ProofConfig.<init>, parameter ecosystem
	at id.walt.signatory.ProofConfig.<init>(Signatory.kt)

But I have not passed any null parameter 

below is the list of parameters I am passing 

ISSUER DID : 
did:ebsi:zkDh3Tw2wNr4tofy62SYHBC
  subject DID : 
did:key:z6MkicPLVe5bX6mEG6kLDcXftpByLh3pqdgWHAgE8b5wypds
 PROOF TYPE 
LD_PROOF
 EXPIRATION 
2022-12-11T10:10:59.389344300Z

But I have checked that there is a last parameter in the createProofConfig()     [Ecosystem Ecosystem]      which should not be null but getting passed as null .

Best Regards
Sethi shivam 

</div>

**Comment by waltkb** [comment]
Still relevant?
